DROP TABLE DESCUENTOS;
DROP TABLE DETALLES_FACTURA_TIENDA;
DROP TABLE LOTES_SET_TIENDA;
DROP TABLE DETALLES_FACTURA_ONLINE;
DROP TABLE DETALLES_INSCRITOS;
DROP TABLE CATALOGOS_LEGO;
DROP TABLE HISTORICO_PRECIOS_JUGUETES;
DROP TABLE PRODUCTOS_RELACIONADOS;
DROP TABLE JUGUETES;
DROP TABLE TEMAS;
DROP TABLE ENTRADAS;
DROP TABLE INSCRIPCIONES_TOUR;
DROP TABLE FECHAS_TOUR;
DROP TABLE FACTURAS_ONLINE;
DROP TABLE TELEFONOS;
DROP TABLE VISITANTES_FANS;
DROP TABLE FACTURAS_TIENDA;
DROP TABLE HORARIOS_ATENCION;
DROP TABLE TIENDAS_LEGO;
DROP TABLE CLIENTES;
DROP TABLE CIUDADES;
DROP TABLE ESTADOS;
DROP TABLE PAISES;

OTRO

-- Tablas de Violeta (dependen de muchas otras)
DROP TABLE DESCUENTOS CASCADE CONSTRAINTS;
DROP TABLE DETALLES_FACTURA_TIENDA CASCADE CONSTRAINTS;
DROP TABLE LOTES_SET_TIENDA CASCADE CONSTRAINTS;
DROP TABLE DETALLES_FACTURA_ONLINE CASCADE CONSTRAINTS;
DROP TABLE DETALLES_INSCRITOS CASCADE CONSTRAINTS;

-- Tablas de Samuel
DROP TABLE PRODUCTOS_RELACIONADOS CASCADE CONSTRAINTS;
DROP TABLE HISTORICO_PRECIOS_JUGUETES CASCADE CONSTRAINTS;
DROP TABLE CATALOGOS_LEGO CASCADE CONSTRAINTS;
DROP TABLE JUGUETES CASCADE CONSTRAINTS;
DROP TABLE TEMAS CASCADE CONSTRAINTS;
DROP TABLE ENTRADAS CASCADE CONSTRAINTS;

-- Tablas de Daniel
DROP TABLE INSCRIPCIONES_TOUR CASCADE CONSTRAINTS;
DROP TABLE FECHAS_TOUR CASCADE CONSTRAINTS;
DROP TABLE FACTURAS_ONLINE CASCADE CONSTRAINTS;
DROP TABLE TELEFONOS CASCADE CONSTRAINTS;
DROP TABLE VISITANTES_FANS CASCADE CONSTRAINTS;
DROP TABLE FACTURAS_TIENDA CASCADE CONSTRAINTS;

-- Tablas principales
DROP TABLE HORARIOS_ATENCION CASCADE CONSTRAINTS;
DROP TABLE TIENDAS_LEGO CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE CIUDADES CASCADE CONSTRAINTS;
DROP TABLE ESTADOS CASCADE CONSTRAINTS;
DROP TABLE PAISES CASCADE CONSTRAINTS;
