ALTER TABLE ESTADOS ADD (
    ID_PAIS NOT NULL REFERENCES(ID) FROM PAISES,
    CONSTRAINT pk_estados PRIMARY KEY(ID,ID_PAIS));

ALTER TABLE CIUDADES ADD (
    ID_PAIS NOT NULL REFERENCES(ID) FROM PAISES,
    ID_ESTADO NOT NULL REFERENCES(ID) FROM ESTADOS,
    CONSTRAINT pk_estados PRIMARY KEY(ID,ID_PAIS,ID_ESTADO));

ALTER 
