CREATE TABLE PAISES
    (ID NUMBER(3) CONSTRAINT pk_paises PRIMARY KEY,
    NOMBRE VARCHAR2(15) NOT NULL,
    GENTILICIO VARCHAR2(10) NOT NULL,
    CONTINENTE VARCHAR2(7) NOT NULL CHECK('AMERICA', 'ASIA', 'AFRICA', 'OCEANIA', 'EUROPA'),
    UE BOOLEAN NOT NULL);

CREATE TABLE ESTADOS
    (ID NUMBER(5) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL);

CREATE TABLE CIUDADES
    (ID NUMBER(8) NOT NULL,
    NOMBRE VARCHAR2(20) NOT NULL);

CREATE TABLE CLIENTES 
    (ID_LEGO NUMBER(8) CONSTRAINT pk_clientes PRIMARY KEY,
    PRIM_NOM VARCHAR2(10) NOT NULL,
    PRIM_APE VARCHAR2(10) NOT NULL,
    SEG_APE VARCHAR2(10) NOT NULL,
    F_NACIM DATE NOT NULL,
    DNI NUMBER(10) NOT NULL,
    SEG_NOM VARCHAR2(10),
    F_VENCE_PASAP DATE,
    PASAPORTE VARCHAR2(12));

CREATE TABLE TIENDAS_LEGO 
    (ID NUMBER(8) CONSTRAINT pk_tiendas PRIMARY KEY,
    NOMBRE VARCHAR2(15) NOT NULL,
    DIRECCION VARCHAR2(150) NOT NULL);

CREATE TABLE HORARIOS_ATENCION
    (DIA DATE CONSTRAINT pk_horarios PRIMARY KEY,
    HORA_ENTR DATE NOT NULL,
    HORA_SAL DATE NOT NULL); 

CREATE TABLE FACTURAS_TIENDA
    (NRO_FACT NUMBER(9) CONSTRAINT pk_fact PRIMARY KEY,
    F_NACIM DATE NOT NULL,
    TOTAL NUMBER(10));

