CREATE TABLE PAISES
    (ID NUMBER(3) CONSTRAINT pk_paises PRIMARY KEY,
    NOMBRE VARCHAR2(15) NOT NULL,
    GENTILICIO VARCHAR2(10) NOT NULL,
    CONTINENTE VARCHAR2(7) NOT NULL CHECK('AMERICA', 'ASIA', 'AFRICA', 'OCEANIA', 'EUROPA'),
    UE BOOLEAN NOT NULL);

CREATE TABLE ESTADOS
    (ID NUMBER(5) NOT NULL,
    ID_PAIS NOT NULL REFERENCES(ID) FROM PAISES,
    NOMBRE VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_estados PRIMARY KEY(ID,ID_PAIS));

